import { ImageSourcePropType } from 'react-native';

export type GardenAssetId = keyof typeof GARDEN_ASSETS;

export const GARDEN_ASSETS = {
  baseGarden: require('../../assets/base/Base_garden.png'),

  campfire: require('../../assets/structures/campfire.png'),
  fence: require('../../assets/structures/fence.png'),
  gardenArchway: require('../../assets/structures/garden_archway.png'),
  gazebo: require('../../assets/structures/gazebo.png'),
  greenhouse: require('../../assets/structures/greenhouse.png'),
  stoneWall: require('../../assets/structures/stone_wall.png'),
  woodenGate: require('../../assets/structures/wooden_gate.png'),
  woodenSign: require('../../assets/structures/wooden_sign.png'),

  bush: require('../../assets/nature/bush.jpg'),
  cherryBlossom: require('../../assets/nature/cherry_blossom.jpg'),
  sapling: require('../../assets/nature/sapling.jpg'),
  willowTree: require('../../assets/nature/willow_tree.jpg'),

  pond: require('../../assets/water/pond.png'),
  stream: require('../../assets/water/stream.png'),
  lillyPads: require('../../assets/water/lilly_pads.png'),
  woodenBridge: require('../../assets/water/wooden_bridge.png'),

  floweringBush: require('../../assets/flowers/flowering_bush.jpg'),
  wildflowerPatch: require('../../assets/flowers/wildflower_patch.jpg'),
  sunflowerPatch: require('../../assets/flowers/sunflower_patch.jpg'),
  lavenderPot: require('../../assets/flowers/lavander_pot.png'),
  hydrangeaPot: require('../../assets/flowers/hydrangea_pot.png'),
  reeds: require('../../assets/flowers/reeds.png'),

  bench: require('../../assets/furniture/bench.png'),
  benchSwing: require('../../assets/furniture/bench_swing.png'),
  birdBath: require('../../assets/furniture/bird_bath.png'),
  hammock: require('../../assets/furniture/hammock.png'),
  treeSwing: require('../../assets/furniture/tree_swing.png'),

  fox: require('../../assets/wildlife/fox.png'),
  squirrel: require('../../assets/wildlife/squirrel.png'),
  dog: require('../../assets/wildlife/dog.png'),
  cat: require('../../assets/wildlife/cat.png'),
  rabbit: require('../../assets/wildlife/rabbit.png'),
  hedgehog: require('../../assets/wildlife/hedgehog.png'),

  blueTit: require('../../assets/birds/blue_tit.png'),
  crow: require('../../assets/birds/crow.png'),
  blackbird: require('../../assets/birds/blackbird.png'),
  owl: require('../../assets/birds/owl.png'),
  robin: require('../../assets/birds/robin.png'),

  bee: require('../../assets/insects/bee.png'),
  butterfly: require('../../assets/insects/butterfly.png'),
  ladybird: require('../../assets/insects/ladybird.png'),
  snail: require('../../assets/insects/snail.png'),
  dragonfly: require('../../assets/insects/dragonfly.png'),

  sun: require('../../assets/sky/sun.png'),
  moon: require('../../assets/sky/moon.png'),
  stars: require('../../assets/sky/stars.png'),
  cloud: require('../../assets/sky/cloud.png'),
  stormCloud: require('../../assets/sky/storm_cloud.png'),
  shootingStar: require('../../assets/sky/shooting_star.png'),
  sparkle: require('../../assets/sky/sparkle.png'),

  cherryBlossomBranch: require('../../assets/seasons/summer/cherry_blossom_branch.png'),
  daffodils: require('../../assets/seasons/summer/daffodils.png'),
  summerWildflowers: require('../../assets/seasons/summer/summer_wildflowers.png'),
  tulips: require('../../assets/seasons/summer/tulips.png'),
  acornBrown: require('../../assets/seasons/autumn/acorn_brown.png'),
  acornGreen: require('../../assets/seasons/autumn/acorn_green.png'),
  autumnLeaves: require('../../assets/seasons/autumn/autumn_leaves.png'),
  birchLeaf: require('../../assets/seasons/autumn/birch_leaf.png'),
  mapleLeaf: require('../../assets/seasons/autumn/maple_leaf.png'),
  oakLeaf: require('../../assets/seasons/autumn/oak_leaf.png'),
  pumpkinGreen: require('../../assets/seasons/autumn/pumpkin_green.png'),
  pumpkinOrange: require('../../assets/seasons/autumn/pumpkin_orange.png'),
  pumpkinWhite: require('../../assets/seasons/autumn/pumpkin_white.png'),
  yellowLeaf: require('../../assets/seasons/autumn/yellow_leaf.png'),
  christmasLights: require('../../assets/seasons/winter/christmas_lights.png'),
  icicles: require('../../assets/seasons/winter/icicles.png'),
  snowflake: require('../../assets/seasons/winter/snowflake.png'),
  snowman: require('../../assets/seasons/winter/snowman.png'),

  lolaBuildSnowman: require('../../assets/Lola/build_snowman.png'),
  lolaHoldingPumpkin: require('../../assets/Lola/holding_pumpkin.png'),
  lolaHoldingUmbrella: require('../../assets/Lola/holding_umbrella.png'),
  lolaJournaling: require('../../assets/Lola/journaling.png'),
  lolaReadingBook: require('../../assets/Lola/reading_book.png'),
  lolaListeningToMusic: require('../../assets/Lola/listening_to_music.png'),
  lolaWateringFlowers: require('../../assets/Lola/watering_flowers.png'),
  lolaStargazing: require('../../assets/Lola/stargazing.png'),
  lolaWrappedInBlanket: require('../../assets/Lola/wrapped_in_blanket.png'),
  lolaDrinkingCoffee: require('../../assets/Lola/drinking_coffee.png'),
  lolaPettingFox: require('../../assets/Lola/petting_fox.png'),
  lolaHoldingRobin: require('../../assets/Lola/holding_robin.png'),
  lolaLyingOnGrass: require('../../assets/Lola/lying_on_grass.png'),
} satisfies Record<string, ImageSourcePropType>;
